export const presets = {
  فارسی: {
    hello: "سلام",
    goodbye: "خداحافظ",
    please: "لطفاً",
    "thank you": "متشکرم",
    yes: "بله",
    no: "نه",
    "how are you?": "حال شما چطوره؟",
    "good morning": "صبح بخیر",
    "good night": "شب بخیر",
    sorry: "متاسفم",
    friend: "دوست",
    family: "خانواده",
    love: "عشق",
    work: "کار",
    school: "مدرسه",
    home: "خانه",
    food: "غذا",
    water: "آب",
    book: "کتاب",
    computer: "کامپیوتر",
    teacher: "معلم",
    student: "دانش آموز",
    city: "شهر",
    country: "کشور",
    language: "زبان",
    car: "ماشین",
    phone: "تلفن",
    music: "موسیقی",
    movie: "فیلم",
    game: "بازی",
    sun: "خورشید",
    moon: "ماه",
    star: "ستاره",
    earth: "زمین",
    sky: "آسمان",
    cloud: "ابر",
    rain: "باران",
    snow: "برف",
    wind: "باد",
    fire: "آتش",
    mountain: "کوه",
    river: "رودخانه",
    sea: "دریا",
    lake: "دریاچه",
    island: "جزیره",
    desert: "بیابان",
    forest: "جنگل",
    tree: "درخت",
    flower: "گل",
    bird: "پرنده",
    fish: "ماهی",
    dog: "سگ",
    cat: "گربه",
    animal: "حیوان",
    human: "انسان",
    child: "کودک",
    adult: "بزرگسال",
    old: "پیر",
    young: "جوان",
    beautiful: "زیبا",
    ugly: "زشت",
    happy: "خوشحال",
    sad: "غمگین",
    angry: "عصبانی",
    excited: "هیجان زده",
    bored: "خسته",
    hungry: "گرسنه",
    thirsty: "تشنه",
    tired: "خسته",
    sleepy: "خواب آلود",
    busy: "مشغول",
    free: "آزاد",
    rich: "ثروتمند",
    poor: "فقیر",
    smart: "هوشمند",
    stupid: "احمق",
    strong: "قوی",
    weak: "ضعیف",
    brave: "شجاع",
    coward: "ترسو",
    fast: "سریع",
    slow: "آهسته",
    early: "زود",
    late: "دیر",
    near: "نزدیک",
    far: "دور",
    inside: "داخل",
    outside: "خارج",
    above: "بالا",
    below: "پایین",
    right: "راست",
    left: "چپ",
    front: "جلو",
    back: "عقب",
    up: "بالا",
    down: "پایین",
  },
  العربية: {
    hello: "مرحبًا",
    goodbye: "وداعًا",
    please: "من فضلك",
    "thank you": "شكرًا",
    yes: "نعم",
    no: "لا",
    "how are you?": "كيف حالك؟",
    "good morning": "صباح الخير",
    "good night": "تصبح على خير",
    sorry: "آسف",
    friend: "صديق",
    family: "عائلة",
    love: "حب",
    work: "عمل",
    school: "مدرسة",
    home: "منزل",
    food: "طعام",
    water: "ماء",
    book: "كتاب",
    computer: "كمبيوتر",
    teacher: "معلم",
    student: "طالب",
    city: "مدينة",
    country: "دولة",
    language: "لغة",
    car: "سيارة",
    phone: "هاتف",
    music: "موسيقى",
    movie: "فيلم",
    game: "لعبة",
    sun: "شمس",
    moon: "قمر",
    star: "نجم",
    earth: "أرض",
    sky: "سماء",
    cloud: "سحابة",
    rain: "مطر",
    snow: "ثلج",
    wind: "ريح",
    fire: "نار",
    mountain: "جبل",
    river: "نهر",
    sea: "بحر",
    lake: "بحيرة",
    island: "جزيرة",
    desert: "صحراء",
    forest: "غابة",
    tree: "شجرة",
    flower: "زهرة",
    bird: "طائر",
    fish: "سمكة",
    dog: "كلب",
    cat: "قط",
    animal: "حيوان",
    human: "إنسان",
    child: "طفل",
    adult: "بالغ",
    old: "قديم",
    young: "شاب",
    beautiful: "جميل",
    ugly: "قبيح",
    happy: "سعيد",
    sad: "حزين",
    angry: "غاضب",
    excited: "متحمس",
    bored: "ضجر",
    hungry: "جائع",
    thirsty: "عطشان",
    tired: "متعب",
    sleepy: "نعسان",
    busy: "مشغول",
    free: "حر",
    rich: "ثري",
    poor: "فقير",
    smart: "ذكي",
    stupid: "غبي",
    strong: "قوي",
    weak: "ضعيف",
    brave: "شجاع",
    coward: "جبان",
    fast: "سريع",
    slow: "بطيء",
    early: "مبكر",
    late: "متأخر",
    near: "قريب",
    far: "بعيد",
    inside: "داخل",
    outside: "خارج",
    above: "فوق",
    below: "تحت",
    right: "يمين",
    left: "يسار",
    front: "أمام",
    back: "خلف",
    up: "أعلى",
    down: "أسفل",
  },
  Français: {
    hello: "bonjour",
    goodbye: "au revoir",
    please: "s'il vous plaît",
    "thank you": "merci",
    yes: "oui",
    no: "non",
    "how are you?": "comment ça va ?",
    "good morning": "bonjour",
    "good night": "bonne nuit",
    sorry: "désolé",
    friend: "ami",
    family: "famille",
    love: "amour",
    work: "travail",
    school: "école",
    home: "maison",
    food: "nourriture",
    water: "eau",
    book: "livre",
    computer: "ordinateur",
    teacher: "professeur",
    student: "étudiant",
    city: "ville",
    country: "pays",
    language: "langue",
    car: "voiture",
    phone: "téléphone",
    music: "musique",
    movie: "film",
    game: "jeu",
    sun: "soleil",
    moon: "lune",
    star: "étoile",
    earth: "terre",
    sky: "ciel",
    cloud: "nuage",
    rain: "pluie",
    snow: "neige",
    wind: "vent",
    fire: "feu",
    mountain: "montagne",
    river: "rivière",
    sea: "mer",
    lake: "lac",
    island: "île",
    desert: "désert",
    forest: "forêt",
    tree: "arbre",
    flower: "fleur",
    bird: "oiseau",
    fish: "poisson",
    dog: "chien",
    cat: "chat",
    animal: "animal",
    human: "humain",
    child: "enfant",
    adult: "adulte",
    old: "vieux",
    young: "jeune",
    beautiful: "beau",
    ugly: "laid",
    happy: "heureux",
    sad: "triste",
    angry: "en colère",
    excited: "excité",
    bored: "ennuyé",
    hungry: "affamé",
    thirsty: "assoiffé",
    tired: "fatigué",
    sleepy: "endormi",
    busy: "occupé",
    free: "libre",
    rich: "riche",
    poor: "pauvre",
    smart: "intelligent",
    stupid: "stupide",
    strong: "fort",
    weak: "faible",
    brave: "courageux",
    coward: "lâche",
    fast: "rapide",
    slow: "lent",
    early: "tôt",
    late: "en retard",
    near: "près",
    far: "loin",
    inside: "à l'intérieur",
    outside: "à l'extérieur",
    above: "au-dessus",
    below: "en dessous",
    right: "droite",
    left: "gauche",
    front: "devant",
    back: "derrière",
    up: "en haut",
    down: "en bas",
  },
};

export const keywordsPreset = [
  "hello:",
  "goodbye",
  "please",
  "thank you",
  "yes",
  "no",
  "how are you?",
  "good morning",
  "good night",
  "sorry",
  "friend",
  "family",
  "love",
  "work",
  "school",
  "home",
  "food",
  "water",
  "book",
  "computer",
  "teacher",
  "student",
  "city",
  "country",
  "language",
  "car",
  "phone",
  "music",
  "movie",
  "game",
  "sun",
  "moon",
  "star",
  "earth",
  "sky",
  "cloud",
  "rain",
  "snow",
  "wind",
  "fire",
  "mountain",
  "river",
  "sea",
  "lake",
  "island",
  "desert",
  "forest",
  "tree",
  "flower",
  "bird",
  "fish",
  "dog",
  "cat",
  "animal",
  "human",
  "child",
  "adult",
  "old",
  "young",
  "beautiful",
  "ugly",
  "happy",
  "sad",
  "angry",
  "excited",
  "bored",
  "hungry",
  "thirsty",
  "tired",
  "sleepy",
  "busy",
  "free",
  "rich",
  "poor",
  "smart",
  "stupid",
  "strong",
  "weak",
  "brave",
  "coward",
  "fast",
  "slow",
  "early",
  "late",
  "near",
  "far",
  "inside",
  "outside",
  "above",
  "below",
  "right",
  "left",
  "front",
  "back",
  "up",
  "down",
];
